### ISSUE TITLE
这是一封信

### ISSUE THREAD

**Issue by qiaokangqi** [yuweiming70/Landscape-Dataset#1]
WeiMing吾友：

见信如唔

        在下最近伏案写作，关乎风景图像分类。偶然路过，见阁下 PO 出数据集，甚是欢喜，至时必手自标注汝之GitHub 地址.

**Comment by koishi70** [comment]
哈哈，道友，此为吾下得360桌面壁纸软件，后扒缓存得之，汝欢喜甚好。
