### ISSUE TITLE
如何解压

### ISSUE THREAD

**Issue by Juzhan** [yuweiming70/Landscape-Dataset#2]
你好，我下载下来后不知如何解压，改为zip后缀名解压也会报错😳

**Comment by djjandXMU** [comment]
更新你的压缩软件，360压缩可以进行解压

**Comment by koishi70** [comment]
压缩包分卷解压缩就行了，也就是直接解压缩，可能是你的压缩软件版本过低之类的，这个应该功能现在应该挺普遍的。
